//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Drawing.IO {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BitStream {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal BitStream() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlas.Drawing.IO.BitStream", typeof(BitStream).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to BitStream lengths must be the same..
        /// </summary>
        public static string Argument_DifferentBitStreamLengths {
            get {
                return ResourceManager.GetString("Argument_DifferentBitStreamLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + offset were out of bounds for the BitStream or count is greater than the number of elements from bitIndex to the end of the BitStream..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_BitStream {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_BitStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + bitIndex exceeds the length of the 8-bit value..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_Byte {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + bitIndex exceeds the length of the 16-bit value..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_Char {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + bitIndex exceeds the length of the 128-bit value..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_Decimal {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + bitIndex exceeds the length of the 16-bit value..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_UInt16 {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_UInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + bitIndex exceeds the length of the 32-bit value..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_UInt32 {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_UInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + bitIndex exceeds the length of the 64-bit value..
        /// </summary>
        public static string Argument_InvalidCountOrBitIndex_UInt64 {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrBitIndex_UInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to count + offset were out of bounds for the array or count is greater than the number of elements from offset to the end of the array..
        /// </summary>
        public static string Argument_InvalidCountOrOffset {
            get {
                return ResourceManager.GetString("Argument_InvalidCountOrOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The bit buffer cannot be null..
        /// </summary>
        public static string ArgumentNull_BitBuffer {
            get {
                return ResourceManager.GetString("ArgumentNull_BitBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The BitStream cannot be null..
        /// </summary>
        public static string ArgumentNull_BitStream {
            get {
                return ResourceManager.GetString("ArgumentNull_BitStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The BufferedStream cannot be null..
        /// </summary>
        public static string ArgumentNull_BufferedStream {
            get {
                return ResourceManager.GetString("ArgumentNull_BufferedStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The CryptoStream cannot be null..
        /// </summary>
        public static string ArgumentNull_CryptoStream {
            get {
                return ResourceManager.GetString("ArgumentNull_CryptoStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The FileStream cannot be null..
        /// </summary>
        public static string ArgumentNull_FileStream {
            get {
                return ResourceManager.GetString("ArgumentNull_FileStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The MemoryStream cannot be null..
        /// </summary>
        public static string ArgumentNull_MemoryStream {
            get {
                return ResourceManager.GetString("ArgumentNull_MemoryStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The NetworkStream cannot be null..
        /// </summary>
        public static string ArgumentNull_NetworkStream {
            get {
                return ResourceManager.GetString("ArgumentNull_NetworkStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Stream cannot be null..
        /// </summary>
        public static string ArgumentNull_Stream {
            get {
                return ResourceManager.GetString("ArgumentNull_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Position must be less than or equal to the Bit Stream Length - 1..
        /// </summary>
        public static string ArgumentOutOfRange_InvalidPosition {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_InvalidPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Capacity must be greater than zero..
        /// </summary>
        public static string ArgumentOutOfRange_NegativeOrZeroCapacity {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NegativeOrZeroCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter must be greater than or equal to zero..
        /// </summary>
        public static string ArgumentOutOfRange_NegativeParameter {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NegativeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Position must be greater than or equal to zero..
        /// </summary>
        public static string ArgumentOutOfRange_NegativePosition {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NegativePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The internal bit buffer&apos;s bit index cannot be greater than 32..
        /// </summary>
        public static string InvalidOperation_BitIndexGreaterThan32 {
            get {
                return ResourceManager.GetString("InvalidOperation_BitIndexGreaterThan32", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Asynchronous operations are not supported by the BitStream class..
        /// </summary>
        public static string NotSupported_AsyncOps {
            get {
                return ResourceManager.GetString("NotSupported_AsyncOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot Flush a BitStream..
        /// </summary>
        public static string NotSupported_Flush {
            get {
                return ResourceManager.GetString("NotSupported_Flush", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The inherited ReadByte method is not supported by the BitStream class. Use one of the overloaded Read methods instead..
        /// </summary>
        public static string NotSupported_ReadByte {
            get {
                return ResourceManager.GetString("NotSupported_ReadByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot Seek on a BitStream. Use Position property instead..
        /// </summary>
        public static string NotSupported_Seek {
            get {
                return ResourceManager.GetString("NotSupported_Seek", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot SetLength of a BitStream..
        /// </summary>
        public static string NotSupported_SetLength {
            get {
                return ResourceManager.GetString("NotSupported_SetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The inherited WriteByte method is not supported by the BitStream class. Use one of the overloaded Write methods instead..
        /// </summary>
        public static string NotSupported_WriteByte {
            get {
                return ResourceManager.GetString("NotSupported_WriteByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot access a closed BitStream..
        /// </summary>
        public static string ObjectDisposed_BitStreamClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_BitStreamClosed", resourceCulture);
            }
        }
    }
}
